### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by BorjaRRR** [OpenMW/android-port#1]
I have a problem when compiling 

infbrr01@Konoha ~/openmw/build-android $ cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/infbrr01/android-cmake/android.toolchain.cmake -DOPENMW_DEPENDENCIES_DIR=/home/infbrr01/AndroidDependencies -DANDROID_NATIVE_API_LEVEL=14 -DPKG_CONFIG_EXECUTABLE=/usr/bin/pkg-config
-- Configuring OpenMW...
-- Could NOT find Git (missing:  GIT_EXECUTABLE) 
CMake Warning at CMakeLists.txt:38 (message):
  Git executable not found

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'libavcodec'
--   found libavcodec, version 56.13.100
-- checking for module 'libavformat'
--   found libavformat, version 56.15.102
-- checking for module 'libavdevice'
--   found libavdevice, version 56.3.100
-- checking for module 'libavutil'
--   found libavutil, version 54.15.100
-- checking for module 'libswscale'
--   found libswscale, version 3.1.101
-- checking for module 'libpostproc'
--   found libpostproc, version 53.3.100
-- checking for module 'libswresample'
--   found libswresample, version 1.1.100
-- checking for module 'libavresample'
--   found libavresample, version 2.1.0
-- Found FFmpeg: /home/infbrr01/AndroidDependencies/lib/libavcodec.a;/home/infbrr01/AndroidDependencies/lib/libavformat.a;/home/infbrr01/AndroidDependencies/lib/libavutil.a;/home/infbrr01/AndroidDependencies/lib/libswscale.a  
-- Using Qt4
CMake Error at /usr/share/cmake-3.2/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:165 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/infbrr01/openmw/build-android/CMakeFiles/CMakeOutput.log".

**Comment by sandstranger** [comment]
it will not be build, because the changes for successfull building with OSG nobody merged to master branche

**Comment by sandstranger** [comment]
It is building now for Android

**Comment by psi29a** [comment]
Yay!
