### ISSUE TITLE
resolve crashes engine on playing video

### ISSUE THREAD

**Issue by sandstranger** [OpenMW/android-port#10]

**Comment by sandstranger** [comment]
It is crashes with 
01-06 19:18:23.253 18431-18431/? I/AEE/AED:     #00 pc 0000000000473368  /system/lib64/egl/libGLES_mali.so
01-06 19:18:23.253 18431-18431/? I/AEE/AED:     #01 pc 0000000000472e0c  /system/lib64/egl/libGLES_mali.so
01-06 19:18:23.253 18431-18431/? I/AEE/AED:     #02 pc 0000000000473bd8  /system/lib64/egl/libGLES_mali.so
01-06 19:18:23.253 18431-18431/? I/AEE/AED:     #03 pc 000000000001f38c  /system/lib64/libc.so (__pthread_start(void*)+52)
01-06 19:18:23.253 18431-18431/? I/AEE/AED:     #04 pc 000000000001b604  /system/lib64/libc.so (__start_thread+16)

**Comment by psi29a** [comment]
Looks like an issue with libGLES_mali.so... the OpenGL ES library for the Mali hardware you are running on. Try testing on another device without mali. 

https://en.wikipedia.org/wiki/Mali_(GPU)

**Comment by sandstranger** [comment]
I will try to test on android emulator , because I have got only one Android device now,. But I think ,that issue not in mali videocard,because engine can play videos without crashes very often

**Comment by sandstranger** [comment]
Android also works on pc O_O
http://www.android-x86.org/

**Comment by sandstranger** [comment]
resolve this crash will be my main task now

**Comment by sandstranger** [comment]
There is no more crashes  with using opengl translation

**Comment by psi29a** [comment]
yay!? what does this mean? It works now?

**Comment by sandstranger** [comment]
With glshim and osg , building with opengl it works without crashes .

**Comment by psi29a** [comment]
how is performance?

**Comment by sandstranger** [comment]
it works with 60 fps on my phone , and there is no any graphics artifacts as it was on gles1
