### ISSUE TITLE
resolve engine crashes

### ISSUE THREAD

**Issue by sandstranger** [OpenMW/android-port#16]

**Comment by sandstranger** [comment]
to avoid crashes engine must be build with -Os and disabled preload cells

**Comment by psi29a** [comment]
Crash might be caused with using OSG < 3.4, as 3.4 fixes crash bug with uncompressed DDS textures.

**Comment by sandstranger** [comment]
It still random crashes with engine , compiled from git

**Comment by sandstranger** [comment]
01-06 19:18:23.253 18431-18431/? I/AEE/AED: #1 pc 0000000000472e0c /system/lib64/egl/libGLES_mali.so
01-06 19:18:23.253 18431-18431/? I/AEE/AED: #2 pc 0000000000473bd8 /system/lib64/egl/libGLES_mali.so
01-06 19:18:23.253 18431-18431/? I/AEE/AED: #3 pc 000000000001f38c /system/lib64/libc.so (__pthread_start(void*)+52)
01-06 19:18:23.253 18431-18431/? I/AEE/AED: #4 pc 000000000001b604 /system/lib64/libc.so (__start_thread+16)
It is crashes with this log . I am not goind to resolve this crash , because log not show where it crashes in openmw

**Comment by sandstranger** [comment]
Yes , it is issue in mali drivers , on adreno videocard game not crashes on external locations . But on Adredno engine simple shows black screen in game
