### ISSUE TITLE
resolve engine crashes on loading 

### ISSUE THREAD

**Issue by sandstranger** [OpenMW/android-port#18]
need to resolve engine crashes on loading locations with opengl emulation

**Comment by sandstranger** [comment]
It crashes with it :
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #00 pc 0000000000057d24  /data/app/com.libopenmw.openmw-3/lib/arm64/libGL.so (glTexImage2D+132)
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #01 pc 0000000000854440  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osg::Texture::applyTexImage2D_load(osg::State&, unsigned int, osg::Image const*, int, int, int) const+2224)
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #02 pc 000000000084aa8c  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osg::Texture2D::apply(osg::State&) const+1844)
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #03 pc 0000000000be8590  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osgMyGUI::Drawable::drawImplementation(osg::RenderInfo&) const+548)
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #04 pc 00000000008ed65c  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osgUtil::RenderLeaf::render(osg::RenderInfo&, osgUtil::RenderLeaf*)+748)
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #05 pc 00000000008e54c4  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osgUtil::RenderBin::drawImplementation(osg::RenderInfo&, osgUtil::RenderLeaf*&)+268)
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #06 pc 00000000008f3c04  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osgUtil::RenderStage::drawImplementation(osg::RenderInfo&, osgUtil::RenderLeaf*&)+644)
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #07 pc 00000000008e57d4  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osgUtil::RenderBin::draw(osg::RenderInfo&, osgUtil::RenderLeaf*&)+156)
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #08 pc 00000000008f2edc  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osgUtil::RenderStage::drawInner(osg::RenderInfo&, osgUtil::RenderLeaf*&, bool&)+108)
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #09 pc 00000000008f55d0  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osgUtil::RenderStage::draw(osg::RenderInfo&, osgUtil::RenderLeaf*&)+2152)
02-25 09:27:00.864 4631-4631/? I/AEE/AED:     #10 pc 00000000008f548c  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osgUtil::RenderStage::draw(osg::RenderInfo&, osgUtil::RenderLeaf*&)+1828)
02-25 09:27:00.865 4631-4631/? I/AEE/AED:     #11 pc 0000000000cd46cc  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osgUtil::SceneView::draw()+476)
02-25 09:27:00.865 4631-4631/? I/AEE/AED:     #12 pc 00000000009b06f0  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osgViewer::Renderer::draw()+2088)
02-25 09:27:00.865 4631-4631/? I/AEE/AED:     #13 pc 00000000007debc4  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osg::GraphicsContext::runOperations()+884)
02-25 09:27:00.865 4631-4631/? I/AEE/AED:     #14 pc 00000000008028a0  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osg::OperationThread::run()+392)
02-25 09:27:00.865 4631-4631/? I/AEE/AED:     #15 pc 00000000007e0294  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (osg::GraphicsThread::run()+84)
02-25 09:27:00.865 4631-4631/? I/AEE/AED:     #16 pc 00000000008b7a1c  /data/app/com.libopenmw.openmw-3/lib/arm64/libopenmw.so (OpenThreads::ThreadPrivateActions::StartThread(void*)+164)
02-25 09:27:00.865 4631-4631/? I/AEE/AED:     #17 pc 000000000001f38c  /system/lib64/libc.so (__pthread_start(void*)+52)
02-25 09:27:00.865 4631-4631/? I/AEE/AED:     #18 pc 000000000001b604  /system/lib64/libc.so (__start_thread+16)
It seems it trying to load null texture

**Comment by sandstranger** [comment]
With last version from git and using dds textures instead png it is not crashes anymore

**Comment by sandstranger** [comment]
it may crashes on showing inventory with this error . This is only crash , which need to be fixed on cm 12.1

**Comment by psi29a** [comment]
Awesome!

**Comment by sandstranger** [comment]
It is no more actual
