### ISSUE TITLE
hey i got an error about fovslider

### ISSUE THREAD

**Issue by deletra11** [OpenMW/android-port#24]
hey i get an error about fovslider and MYGUI can you help me to get it to work??

MyGUI EXCEPTION : WIDGET NAME 'FOVSlider' in layout
'openmw_settings_window.layout' not found
in MYGUI at /home/sandstranger/Android/openmw/apps/openmw/mwgui/layout.cpp (line 75)

plzz help :)

Im new to this

**Comment by sandstranger** [comment]
this issue was connected with old openmw assets
