### ISSUE TITLE
boost::filesystem::directory_iterator::operator++: Function not implemented 

### ISSUE THREAD

**Issue by xyzz** [OpenMW/android-port#35]
As reported in https://forum.openmw.org/viewtopic.php?f=2&t=4898&start=20#p52420 - looks like a boost bug: https://gist.github.com/webmaster128/5912a70d100e9ef341df67b177c465d6

**Comment by psi29a** [comment]
Can this be inlined in OpenMW or built with another version of boost?

**Comment by xyzz** [comment]
I'm working on this in https://github.com/OpenMW/android-port/tree/issue-35

**Comment by xyzz** [comment]
apk for the user to test: [issue-35.zip](https://github.com/OpenMW/android-port/files/1660505/issue-35.zip)

**Comment by TopherLee513** [comment]
Testing...

**Comment by psi29a** [comment]
Can this be resolved?

**Comment by xyzz** [comment]
It's fixed in #37
