### ISSUE TITLE
Error running build.sh

### ISSUE THREAD

**Issue by matthewlswanson** [OpenMW/android-port#40]
When I am running the build shell script I get an error every time, no matter what OS I'm running it on. Here is the error: 

Download and set up the NDK
~/android-port/buildscripts/downloads ~/android-port/buildscripts
~/android-port/buildscripts/toolchain ~/android-port/buildscripts
Making standalone toolchain for architecture arm
./include/setup-ndk.sh: line 22: ./ndk/build/tools/make_standalone_toolchain.py:
No such file or directory.

Am I missing something?
I installed gcc and g++, cmake 3.7, android-sdk

**Comment by xyzz** [comment]
do you have python installed?

**Comment by matthewlswanson** [comment]
Yes, it is installed by default (I am using Ubuntu and Debian). The odd thing is it was working on a different machine with Ubuntu until I ran out of disk space and killed the OS

**Comment by xyzz** [comment]
well if you ran out of disk space it probably failed to unzip the ndk and it's missing a bunch of files, wipe it and start over

**Comment by matthewlswanson** [comment]
Sorry I didn't differentiate. I first had the build script working but ran out of space but that is a different error. The error I am posting about is on the machines with plenty of disk space left.

**Comment by xyzz** [comment]
ok, check if the `make_standalone_toolchain.py` exists and if you can run it from command line

**Comment by matthewlswanson** [comment]
I'm not finding that file in the android-port directory, using find or locate

**Comment by xyzz** [comment]
it should be in `buildscripts/toolchain/ndk/build/tools/make_standalone_toolchain.py`

**Comment by matthewlswanson** [comment]
Here's exactly what happens when I run it


mswanson@debian:~/android-port/buildscripts$ ./build.sh 

================================================================================

Build configuration:
 - Architecture: arm
 - Build type: release
 - AddressSanitizer: false

 ------------------------------------------------------------------------------ 

Computed flags:
 - CFLAGS: -fPIC -O2
 - CXXFLAGS: -fPIC -frtti -fexceptions -O2
 - LDFLAGS: -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -Wl,--exclude-libs,libunwind.a -stdlib=libc++ -L/home/mswanson/android-port/buildscripts/toolchain/ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/

================================================================================
(Please run ./clean.sh manually if you modify any of the options)

==> Download and set up the NDK
~/android-port/buildscripts/downloads ~/android-port/buildscripts
~/android-port/buildscripts/toolchain ~/android-port/buildscripts
==> Making standalone toolchain for architecture arm
./include/setup-ndk.sh: line 22: ./ndk/build/tools/make_standalone_toolchain.py: No such file or directory
mswanson@debian:~/android-port/buildscripts$

**Comment by psi29a** [comment]
looks like you don't have ndk running, or it isn't installed in the directory you are running the script from.

**Comment by matthewlswanson** [comment]
Isn't the script supposed to be installing it?

**Comment by matthewlswanson** [comment]
I downloaded and unzipped android-ndk into buildscripts directory and ran the script, had the exact same error

**Comment by matthewlswanson** [comment]
Interesting reinstalled Ubuntu on the machine that was working that ran out of disk space, installed python-pip and used that to install cmake, now it seems to me running. Hope it doesn't run out of space again...

**Comment by psi29a** [comment]
OK, so this issue can be closed? :)

**Comment by matthewlswanson** [comment]
Yes I just got the app installed! Now I have to get the data files from steam or my cds. Are there instructions  for this or do I just install it on windows and copy/paste the files?

**Comment by psi29a** [comment]
Instructions are on the forums. ;)
