### ISSUE TITLE
Add the app on F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [OpenMW/android-port#58]
...without non-free Crashlytics libs.

Ref: https://gitlab.com/fdroid/fdroiddata/merge_requests/4071

Ref: https://github.com/OpenMW/android-port/pull/56

Log: https://gist.github.com/licaon-kter/e2ab352c5e8b0b0639ff16af3017f1b0

**Comment by ClockGen** [comment]
Yes, Android version of OpenMW is being included in F-Droid right now, however, crashlytics is a proprietary library and apps with it cannot be included. Is it possible to remove them (if they are not necessary), or make a separate build flavor without them for F-Droid?
@xyzz

**Comment by terabyte25** [comment]
If necessary, I can go ahead and make a branch to remove it.

**Comment by xyzz** [comment]
If you send me a pr to add a no-crashlytics flavor (to my repository, not this one) I'll merge it, but I don't plan on working on it myself anytime soon.

**Comment by terabyte25** [comment]
https://github.com/xyzz/openmw-android/pull/3

**Comment by licaon-kter** [comment]
@xyzz @psi29a 

Is there any structure to the release sched?

Ok, I guess you follow the main openmw project, but I see that versionCode gets updated here without any relation (eg. I've started adapting this for F-Droid at version 6...now it's at 9 already).

I'm updating [the metadata](https://gitlab.com/fdroid/fdroiddata/merge_requests/4071#note_164290363) to actually publish the app and I'd like to know what's the pace here, while the main project has a (multi?) year release cycle, when would we decide to push a new Android version? Can we do it when, say, the in app mods setup interface is ready? When you remove OpenSceneGraph-Fork? etc

Will you then bump the minor versioning, say 0.40.1, so you still follow the main project but have things versioned on the Android side?

**Comment by xyzz** [comment]
Currently there isn't one. What I plan to do is when all main features are complete (mod manager, new installation flow, etc) I'll most likely change the package name to something I own, maybe shuffle config files around in a backwards-incompatible way, and start signing builds with proper release keys (so that it can be published on google play). At the same time, I plan to split the apk into two branches, the main one will track openmw releases and the nightly would be openmw nightlies (probably more like weeklies or monthlies). That said, even the main branch might get updated at any time if there's any breaking bugs or major changes I want to get in. The best way to track would be to look at the release tags published in the repo.

**Comment by licaon-kter** [comment]
> I'll most likely change the package name to something I own

...with the app from your repo, right?

@psi29a What about this repo?

> The best way to track would be to look at the release tags published in the repo.

That's fine, we can even enable autoupdate so fdroidbot can just pull/build/publish new releases after you've tagged them, that would be awesome.

@psi29a What about this repo, no tags here? Plans?

>  it can be published on google play

That will be a thing? Ok, I've read something about _"not advertising pictures of the app running"_ or something, and while F-Droid is a small fish in mobile apps publishing, an app on Google Play store won't trigger Beth's lawyers into action?

Regarding the split we would have a `com.libopenmw.openmw` for this repo, an `is.xyz.openmw` and `is.xyz.openmw_nightly` for yours? And that's ok, I'll just add more apps to F-Droid :))

I've seen that now your repo @xyzz is no longer marked as a fork, what exactly is the status here? What repo would a OpenMW F-Droid release be based on?

I'd like to merge the F-Droid build and have that going, but I'd like it to not change app IDs and source repo tomorrow :P (eg. https://github.com/xyzz/openmw-android/pull/5 doesn't enlighten at all).

**Comment by xyzz** [comment]
> ...with the app from your repo, right?

Yeah.

> That will be a thing? Ok, I've read something about "not advertising pictures of the app running" or something, and while F-Droid is a small fish in mobile apps publishing, an app on Google Play store won't trigger Beth's lawyers into action?

From my experience with Google Play they're quite reasonable and so long as there's no copyrighted content (including screenshots, so I'll just publish screenshots of the configuration menu, mod manager, etc) it will be fine.

> Regarding the split we would have a com.libopenmw.openmw for this repo, an is.xyz.openmw and is.xyz.openmw_nightly for yours? And that's ok, I'll just add more apps to F-Droid :))

Something like that, I suppose I still need to get approval to use the name.

> I've seen that now your repo @xyzz is no longer marked as a fork, what exactly is the status here? What repo would a OpenMW F-Droid release be based on?

I asked github support to remove the fork status since my repo's not really maintained as a fork (if anything it's openmw/android-port that's the fork now).

**Comment by licaon-kter** [comment]
I've been following @xyzz 's repo, updating the metadata, patching stuff, build tested all 4 arches. All is fine...this is meargeable in F-Droid...


But...what app exactly? @psi29a ?

OpenMW "original" ? OpenMW Xyzz's Edge ?

**Comment by licaon-kter** [comment]
@xyzz Ok so `is.xyz.owm` from your repo and `com.libopenmw.openmw` from this repo, right?

One thing, do Tag consistently, eg. today it's versionCode 14 but tag says 13?

**Comment by xyzz** [comment]
> Ok so is.xyz.owm from your repo

Yes

> and com.libopenmw.openmw from this repo, right?

Well ultimately that's not up to me, but currently yes.

> One thing, do Tag consistently, eg. today it's versionCode 14 but tag says 13?

Yeah that was my bad, I've fixed the tag now.

**Comment by licaon-kter** [comment]
I'll wait for the bugsnag merge then...

In the mean time, I'd like to enable auto updates, but the current `versionName` generation can't be used by the updatebot, as (for security reasons) it doesn't execute functions in Gradle files: https://github.com/xyzz/openmw-android/blob/master/app/build.gradle#L19

**Comment by xyzz** [comment]
I'm not sure I understand. Isn't it building the whole project, running the (untrusted) build.sh script? Then why is it a problem to run functions in Gradle files?

**Comment by licaon-kter** [comment]
@xyzz  ¯\_(ツ)_/¯

**Comment by Bubu** [comment]
The project is built in a VM that gets thrown away afterwards. The update checks don't happen inside a VM currently.

**Comment by xyzz** [comment]
Can the update check use the git tag or versionCode instead of versionName?

**Comment by licaon-kter** [comment]
It gets them, but then versionName from metadata doesn't equal one from the build APK.

**Comment by xyzz** [comment]
Can it grab the version from the built APK? Either way, this sounds like an f-droid issue... not sure what I can do to fix. The versionName isn't even available until we build, since it's based on OpenMW's version file generated during build process.

**Comment by licaon-kter** [comment]
@xyzz It grabs it then compares it with the one in metadata. Then it will fail :)

Yes, I understand how it's generated here....

Not a blocker, FYI. Will see how this improves in the future (from F-Droid's side)

**Comment by licaon-kter** [comment]
@xyzz Here's a thought... use the Tag without the `v`, so both end up as `0.46.0-16`, and that will make F-Droid pick up the new release.

Eg. now it will set both `commit:` and `versionName` to `v0.46.0-15` and that is wrong since versionName has no `v`

**Comment by xyzz** [comment]
Sure I can do that.

**Comment by licaon-kter** [comment]
The deed has been done.... now we wait... :grin:

**Comment by licaon-kter** [comment]
First try:
* OpenMW - build VM didn't start (happens sometimes): https://f-droid.org/wiki/page/com.libopenmw.openmw/lastbuild_8
* OMW - cert error on Github: https://f-droid.org/wiki/page/is.xyz.omw/lastbuild_17

Maybe next cycle...

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroidserver/issues/657 :(

**Comment by licaon-kter** [comment]
@xyzz Should I tweak the Tags to pickup only non-nightly entries for OMW (those ending in a number nor a letter)? Ref. https://gitlab.com/fdroid/fdroiddata/commit/506f9cb220ccf04f6d45fd83afcb39a0a75e66f4

Or it does not matter anyway (it has not yet been build by F-Droid due to some unknown issue at this moment) since OMW is rather "unsable" or "edge"?

**Comment by xyzz** [comment]
The nightly ones have a different application id so yeah probably shouldn't build them into is.xyz.omw.

**Comment by licaon-kter** [comment]
@xyzz obviously... The id slipped my mind, it will fail at the very end.

**Comment by licaon-kter** [comment]
Both apps have been build finally, waiting for sign&publish.

**Comment by licaon-kter** [comment]
Always use the F-Droid client to get info on new apps and timely updates notifications for the installed apps.

That being said, refresh your repos, OpenMW, OMW and OMW Nightly are available. 

;)

**Comment by licaon-kter** [comment]
OMW (xyzz's apps) build fine and updates... What's the status of this app? Or OMW should be considered "official"?
