### ISSUE TITLE
App menu - don't force landscape

### ISSUE THREAD

**Issue by licaon-kter** [OpenMW/android-port#63]
...it's unwieldy and useless, switch when I press START.

**Comment by licaon-kter** [comment]
@xyzz The Mods view is not forced Landscape, I can freely rotate it, is that intended ( I hope so :) ) or just a glitch?

**Comment by xyzz** [comment]
Yes I do plan to make both portrait, but it's non-trivial (as in, the game just doesn't start anymore if the main menu's in portrait for some reason I haven't yet investigated)

**Comment by licaon-kter** [comment]
Fixed I guess...
