### ISSUE TITLE
Can't build `arm64` unless I build `arm` too?

### ISSUE THREAD

**Issue by licaon-kter** [OpenMW/android-port#64]
...since `app/src/main/assets` are missing, as the build script only copies them on `arm`: https://github.com/OpenMW/android-port/blob/master/buildscripts/build.sh#L184

I guess the same for x86 and x86_64.

**Comment by terabyte25** [comment]
The buildscript always "assumes" you're doing a full-build or building with arm.

Stupid, I know. Just comment it the conditional out.
