### ISSUE TITLE
Add option to hide mouse arrow

### ISSUE THREAD

**Issue by licaon-kter** [OpenMW/android-port#68]
...since there's no need for it now that absolute mouse control exists.

/PS: once #67 gets fixed ofcourse

**Comment by Zebrazilla** [comment]
Great. However please also keep the option for showing mouse arrow & relative mouse control as it's still needed for controllers.

While at it, also please consider some type of implementation of #59 so that relative mouse control over joystick becomes more useful on Android.

**Comment by licaon-kter** [comment]
Fixed in https://github.com/xyzz/openmw-android/commit/80e4674c9e244e06b508835f514feb15ff7ab2cb
