### ISSUE TITLE
rebuild all dependencies on crystax ndk 10.3.0 and gcc5.3

### ISSUE THREAD

**Issue by sandstranger** [OpenMW/android-port#9]

**Comment by sandstranger** [comment]
game crashes on all crystax ndk versions above 10.1.0 with
 #00 pc 000000000005f3cc  /system/lib64/libc.so (tgkill+8)
01-01 21:15:59.743 6184-6184/? I/AEE/AED:     #01 pc 0000000000020304  /system/lib64/libc.so (pthread_kill+160)
01-01 21:15:59.743 6184-6184/? I/AEE/AED:     #02 pc 0000000000021838  /system/lib64/libc.so (raise+28)
01-01 21:15:59.743 6184-6184/? I/AEE/AED:     #03 pc 0000000000026130  /data/app/com.libopenmw.openmw-1/lib/arm64/libcrystax.so (abort+60)
So game works only on crystax ndk 10.1.0 , On google ndk it even not compiled .

**Comment by sandstranger** [comment]
On last crystax ndk version 10.3.1 it is crashes if enable sound in engine with
7 21:59:24.358 304-878/? D/AudioFlinger_Threads: threadLoop_sleepTime write muted data to hw
01-07 21:59:24.358 304-878/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
01-07 21:59:24.365 5529-5529/? I/AEE/AED: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-07 21:59:24.365 5529-5529/? I/AEE/AED: Build fingerprint: 'alps/full_h560/h560:5.1.1/LMY48B/1448649941:user/test-keys'
01-07 21:59:24.365 5529-5529/? I/AEE/AED: Revision: '0'
01-07 21:59:24.365 5529-5529/? I/AEE/AED: ABI: 'arm64'
01-07 21:59:24.365 5529-5529/? I/AEE/AED: pid: 4902, tid: 5527, name: AudioTrack  >>> com.libopenmw.openmw <<<
01-07 21:59:24.365 5529-5529/? I/AEE/AED: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7f82703fe0
01-07 21:59:24.370 304-878/? D/AudioFlinger_Threads: threadLoop_sleepTime write muted data to hw
01-07 21:59:24.374 5529-5529/? I/AEE/AED:     x0   0000000000000000  x1   0000000000c00000  x2   0000000000c00000  x3   0000000000000000
01-07 21:59:24.374 5529-5529/? I/AEE/AED:     x4   000000000000ac44  x5   0000007f77d88978  x6   0000000000000000  x7   000000003b9aca00
01-07 21:59:24.374 5529-5529/? I/AEE/AED:     x8   0000000000000200  x9   0000007f78c59000  x10  0000007f827ff348  x11  0000000000000001
01-07 21:59:24.374 5529-5529/? I/AEE/AED:     x12  0000000000000001  x13  0000000000000001  x14  0000000000000000  x15  0000007f827ff2f0
01-07 21:59:24.374 5529-5529/? I/AEE/AED:     x16  0000007f77fecfb8  x17  0000007f77fbd974  x18  0000000000000000  x19  0000007f82704058
01-07 21:59:24.374 5529-5529/? I/AEE/AED:     x20  0000007f78c41000  x21  0000007f78c47000  x22  0000000000000000  x23  0000007f78c57000
01-07 21:59:24.374 5529-5529/? I/AEE/AED:     x24  0000000000000002  x25  0000007f78c55004  x26  0000007f78c59000  x27  0000000000000004
01-07 21:59:24.374 5529-5529/? I/AEE/AED:     x28  0000000000000000  x29  0000007f82704020  x30  0000007f77fbd998
01-07 21:59:24.374 5529-5529/? I/AEE/AED:     sp   0000007f82704020  pc   0000007f77fbd974  pstate 0000000060000000
01-07 21:59:24.375 5529-5529/? I/AEE/AED: backtrace:
01-07 21:59:24.375 5529-5529/? I/AEE/AED:     #00 pc 000000000008d974  /data/app/com.libopenmw.openmw-2/lib/arm64/libcrystax.so (lrintf)
01-07 21:59:24.375 5529-5529/? I/AEE/AED:     #01 pc 000000000008d994  /data/app/com.libopenmw.openmw-2/lib/arm64/libcrystax.so (lrintf+32)
Without sound engine works

**Comment by psi29a** [comment]
But with 10.3.1, that is without bionic? I'm happy with that. :)

**Comment by sandstranger** [comment]
As I know ,crystax ndk 10.1.0 used bionic libc only for pthreads .

**Comment by sandstranger** [comment]
It seems it crashes on openal on lrintf , I will try rebuild openal with disabled HAVE_LRINTF at eveing

**Comment by psi29a** [comment]
Would be great if you found the cause!  I think for most libraries, you only need the bare-minimal.

**Comment by sandstranger** [comment]
After replacing  llrint ,llrintf ,lrint and others methods in ffmpeg and openal by custom methods ,engine started work without crashes with sound

**Comment by sandstranger** [comment]
It is crashed on ffmpeg on armv7 arch with 
1-08 23:32:57.633 382-382/? W/ADB_SERVICES: entered. LS(10128) fd=18
01-08 23:32:57.636 1120-1984/? D/Surface: Surface::setBuffersDimensions(this=0x7f79a2ec00,w=75,h=1920)
01-08 23:32:57.637 29698-29698/? I/AEE/AED:     r0 00000000  r1 00000000  r2 00000000  r3 00000000
01-08 23:32:57.637 29698-29698/? I/AEE/AED:     r4 00000000  r5 00000000  r6 00000000  r7 00000000
01-08 23:32:57.637 29698-29698/? I/AEE/AED:     r8 00000000  r9 00000000  sl c7ce346c  fp dd638948
01-08 23:32:57.637 29698-29698/? I/AEE/AED:     ip dd924e14  sp da35eda0  lr 7fefffff  pc e0690afc  cpsr 60010010
01-08 23:32:57.638 29698-29698/? I/AEE/AED: backtrace:
01-08 23:32:57.638 29698-29698/? I/AEE/AED:     #00 pc 0006fafc  /data/app/com.libopenmw.openmw-2/lib/arm/libcrystax.so (frexp+20)
01-08 23:32:57.638 29698-29698/? I/AEE/AED:     #01 pc 015abc90  /data/app/com.libopenmw.openmw-2/lib/arm/libopenmw.so (av_d2q+120)

**Comment by sandstranger** [comment]
It is work now on armv7 arch

**Comment by psi29a** [comment]
:D  yay, I'm so glad you are keeping at it.  Time to update the wiki build page and if you could give me some binaries to test on my armv7 mobile please?

**Comment by sandstranger** [comment]
Update : for building engine for armv7 hard was used android cmake toolchain with this PR
https://github.com/taka-no-me/android-cmake/pull/59

**Comment by sandstranger** [comment]
Update : for building engine for armv7 hard was used android cmake toolchain with this PR
taka-no-me/android-cmake#59
